![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [159]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [160]:
a=schools[((schools['average_math']/800)*100)>=80]
print(a.head())

                                          school_name  ... percent_tested
0   New Explorations into Science, Technology and ...  ...            NaN
45                      Eleanor Roosevelt High School  ...           86.0
68  High School for Mathematics, Science, and Engi...  ...           92.6
88                             Stuyvesant High School  ...           97.4
93                Staten Island Technical High School  ...           99.7

[5 rows x 7 columns]

In [161]:
best_math_schools = a[['school_name', 'average_math']].sort_values('average_math',ascending=False)
schools['total_SAT']=schools['average_math']+schools['average_reading']+schools['average_writing']

In [162]:
top_10_schools=schools.sort_values('total_SAT',ascending=False)[['school_name','total_SAT']].head(10)

In [163]:
ba=schools.groupby('borough')['total_SAT'].agg(['count','mean','std']).round(2)

In [164]:
largest_std_dev=ba[ba['std']==ba['std'].max()]
largest_std_dev=largest_std_dev.rename(columns={'count':'num_schools','mean':'average_SAT','std':'std_SAT'})